### ISSUE TITLE
Returning more than one implementation of HTMLDocument

### ISSUE THREAD

**Issue by maciejtrybilo** [vapor-community/vapor-elementary#3]
I've encountered the problem illustrated in the code below. When I want to return more than one kind of page from one endpoint, I'm struggling with the type system. The return value expects `HTMLResponse` to be parametrised with a concrete type, but that only lets me return one type of page.

The only workaround I could find was to switch on the page type inside of the `HTMLDocument` implementation, but that's pretty awful. 

```
struct TodoController: RouteCollection {
    
    func boot(routes: RoutesBuilder) throws {
        
        routes.get("todo", ":todoId", use: getTodos)
    }
    
    @Sendable func getTodo(req: Request) async throws -> HTMLResponse<???> {
        
        let todoId = req.parameters.get("todoId")!
        
        guard let todo = try await Todo
            .query(on: req.db)
            .filter(\.$id == todoId)
            .first() else {
            return HTMLResponse { NotFoundPage() }
        }
        
        return HTMLResponse { TodosPage(todo: todo) }
    }
}

struct TodosPage: HTMLDocument {
    
    var todo: Todo
    
    var title: String = "Todo"

    var head: some HTML {
        meta(.name(.viewport), .content("width=device-width, initial-scale=1"))
    }

    var body: some HTML {
        todo.description
    }
}

struct NotFoundPage: HTMLDocument {
        
    var title: String = "Not found"

    var head: some HTML {
        meta(.name(.viewport), .content("width=device-width, initial-scale=1"))
    }

    var body: some HTML {
        "Todo Not Found"
    }
}
```

**Comment by sliemeobn** [comment]
hi, sorry for the late response, I somehow did not see or get a notification for this.

this is a very good question, and I haven't come to a good "this is the way" conclusion yet.

for errors specifically, I could imagine throwing specific errors and using a middleware to convert them to proper html responses. this way the return type of the handler can stay a single discrete type for the "normal" case.

for cases where the page simply shows conditional content, I think a switch inside the HTML struct is actually the best way.

if both these methods do not fit well, there will be no way around a type-erased return type of some sort. a simple way I can think of is to return `Response` directly, like so:
```swift
@Sendable func myHandler(request: Request) async throws -> Response {
    return try await HTMLResponse {
        "I will be type-erased"
    }.encodeResponse(for: request)
}
```

**Comment by sliemeobn** [comment]
the latest release uses a type-erased `HTMLResponse` type, which should resolve the ergonomics issue here.
https://github.com/vapor-community/vapor-elementary/releases/tag/0.2.0

**Comment by maciejtrybilo** [comment]
Thank you!
