### ISSUE TITLE
Support Hyperscript attribute

### ISSUE THREAD

**Issue by maciejtrybilo** [vapor-community/vapor-elementary#5]
[Hyperscript](https://hyperscript.org) complements HTMX nicely. It would be great to add an attribute for Hyperscript code, so e.g.
```
.custom(name: "_", value: "on submit trigger closeModal")
```
could be written something like 
```
.hs("on submit trigger closeModal")
```

Presumably adding a new library analogously to https://github.com/sliemeobn/elementary-htmx.git  would be most orderly even though it would just be adding one attribute?

**Comment by sliemeobn** [comment]
hmm... nice idea.
but since it really just the one attribute, its own package feels like a lot of song and dance 🤔

I can imagine simply adding it to the htmx package, or, maybe just documenting how to extend this in you own package.
it is basically three lines of code... anyone can write them.

thoughts?

**Comment by maciejtrybilo** [comment]
Makes sense. Should I open a PR for htmx package?

**Comment by sliemeobn** [comment]
@maciejtrybilo that would be fantastic, thanks.

I am thinking a separate target with `.hyperscript` attribute?

**Comment by sliemeobn** [comment]
@maciejtrybilo any news on this?

I'd rather close the issue here, since it is really not the connected to the vapor integration package.
feel free to start a PR or raise the issue again on the htmx package repo 🙏

**Comment by maciejtrybilo** [comment]
@sliemeobn I'm sorry about the delay, the PR is ready! https://github.com/sliemeobn/elementary-htmx/pull/13 Please let me know if you would like any changes.
